server.port=8888
spring.application.name=config-server
spring.profiles.active=native

spring.cloud.config.server.native.search-locations[0]=classpath:config/core/event-service/
spring.cloud.config.server.native.search-locations[1]=classpath:config/core/user-service/
spring.cloud.config.server.native.search-locations[2]=classpath:config/core/request-service/
spring.cloud.config.server.native.search-locations[3]=classpath:config/stats-service/{application}
spring.cloud.config.server.native.search-locations[4]=classpath:config/infra/{application}
spring.cloud.config.server.native.search-locations[5]=classpath:config/core/comment-service/

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always