server.port=0
spring.application.name=config-server
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=classpath:config/

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always