spring.application.name=analyzer
grpc.server.port=0
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://analyzer-db:5432/analyzer}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:analyzer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:analyzer}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql