server.port=0
spring.application.name=request-service
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.client.health-check.enabled=true
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

grpc.client.collector.enabled=${GRPC_CLIENT_COLLECTOR_ENABLED:false}