server.port=8080
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=main-service-route
spring.cloud.gateway.routes[0].uri=lb://MAIN-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader