server.port=8080
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/users/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[1].id=request-service-events-route
spring.cloud.gateway.routes[1].uri=lb://REQUEST-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/{userId}/events/{eventId}/requests/**
spring.cloud.gateway.routes[1].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[2].id=request-service-route
spring.cloud.gateway.routes[2].uri=lb://REQUEST-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/{userId}/requests/**
spring.cloud.gateway.routes[2].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[3].id=comment-service-admin-route
spring.cloud.gateway.routes[3].uri=lb://COMMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/comments/**
spring.cloud.gateway.routes[3].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[4].id=comment-service-events-comments-route
spring.cloud.gateway.routes[4].uri=lb://COMMENT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/events/{eventId}/comments/**
spring.cloud.gateway.routes[4].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[5].id=comment-service-private-route
spring.cloud.gateway.routes[5].uri=lb://COMMENT-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/events/{eventId}/users/{commentatorId}/comment/**
spring.cloud.gateway.routes[5].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[6].id=comment-service-reactions-route
spring.cloud.gateway.routes[6].uri=lb://COMMENT-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/comments/**
spring.cloud.gateway.routes[6].filters[0]=PreserveHostHeader

spring.cloud.gateway.routes[7].id=event-service-route
spring.cloud.gateway.routes[7].uri=lb://EVENT-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/**
spring.cloud.gateway.routes[7].filters[0]=PreserveHostHeader

eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/