spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/users/**

spring.cloud.gateway.routes[1].id=request-service-route
spring.cloud.gateway.routes[1].uri=lb://REQUEST-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/*/requests/**

spring.cloud.gateway.routes[2].id=event-service-route
spring.cloud.gateway.routes[2].uri=lb://EVENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/events/**,/categories/**,/compilations/**,/admin/categories/**,/admin/compilations/**,/admin/events/**,/users/*/events/**