spring.application.name=aggregator
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
aggregator.kafka.user-actions-topic=stats.user-actions.v1
aggregator.kafka.events-similarity-topic=stats.events-similarity.v1
aggregator.kafka.consumer-group=aggregator

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.client.health-check.enabled=true
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true