spring.application.name=aggregator
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
aggregator.kafka.user-actions-topic=stats.user-actions.v1
aggregator.kafka.events-similarity-topic=stats.events-similarity.v1
aggregator.kafka.consumer-group=aggregator